title: Concert Vitae
baseurl: "/concert-vitae"
url: "https://kyrremann.no/concert-vitae"
desc: >
  I enjoy going to concerts, but sometimes have a hard time remembering which
  concerts I've been to. This is a simple overview of most of them.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - function
