title: Concert Vitae
baseurl: "/mcv"
url: "https://kyrremann.no/mcv"
desc: >
  I enjoy going to concerts, but sometimes have a hard time remembering which
  concerts I've been to. This is a simple overview of most of them.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
